service: gram-coffee

frameworkVersion: "2"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-plugin-split-stacks
  # - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  profile: gram-coffee
  region: ap-southeast-1
  stage: stg
  apiGateway:
    restApiId: 17ppqr8hzh
    restApiRootResourceId: dzhmb2sh05
    binaryMediaTypes:
      - "*/*"
  lambdaHashingVersion: 20201221
  environment:
    COGNITO_USER_POOL_ID: ap-southeast-1_uOxnNkgRG
    COGNITO_CLIENT_ID: 6jmjvuul77mt72osb72bo4ali2
    ENV_REGION: ${self:provider.region}
    ADMIN_SECRET_TOKEN: 9TBydgrLKt
    ACCESS_KEY_ID: AKIARUDCRWVX6T2JB7HX
    SECRET_ACCESS_KEY: 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
  # vpc:
  #   securityGroupIds:
  #     - sg-0344124f1db34f905
  #   subnetIds:
  #     - subnet-07524c89552bc68a3
  versionFunctions: false

functions:
  user-registration:
    handler: src/v1/auth/registration/index.handler
    memorySize: 256
    timeout: 30
    role: NSBServicesLambdaRole
    events:
      - http:
          path: v1/auth/registration
          method: POST
          cors: true

  user-confirmation:
    handler: src/v1/auth/confirmation/index.handler
    memorySize: 256
    timeout: 30
    role: NSBServicesLambdaRole
    events:
      - http:
          path: v1/auth/confirmation
          method: POST
          cors: true

  user-login:
    handler: src/v1/auth/login/index.handler
    memorySize: 256
    timeout: 30
    role: NSBServicesLambdaRole
    events:
      - http:
          path: v1/auth/login
          method: POST
          cors: true

  user-change-password:
    handler: src/v1/auth/changePassword/index.handler
    memorySize: 256
    timeout: 30
    role: NSBServicesLambdaRole
    events:
      - http:
          path: v1/auth/change_password
          method: POST
          cors: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true # This is required
  serverless-offline:
    httpPort: 4000

package:
  patterns:
    - "!tests/**"
    - "!tests-integration/**"
    - "!.idea/**"
    - "!serverless-configs/**"
    - "!envs/**"
    - "!support/**"
    - "!node_modules/.cache/**"
    - "!scripts/**"

resources:
  # - ${file(./cloudformation/cognito-user-pool.yml)}
  # - ${file(./resources/api-main.yml)}
  # - ${file(./resources/api-authorizer.yml)}
  - Resources:
      NSBServicesLambdaRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - lambda.amazonaws.com
                    - cognito-idp.amazonaws.com
                Action:
                  - sts:AssumeRole
          Path: "/"
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          Policies:
            - PolicyName: gram-coffee-user-policy
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - ses:*
                    Resource: arn:aws:ses:*
                  - Effect: Allow
                    Action:
                      - cognito-idp:AdminCreateUser
                      - cognito-idp:AdminUpdateUserAttributes
                      - cognito-idp:ListUsers
                      - cognito-idp:AdminGetUser
                      - cognito-idp:AdminDeleteUser
                      - cognito-idp:AdminSetUserPassword
                      - cognito-idp:ForgotPassword
                      - cognito-idp:ConfirmForgotPassword
                      - cognito-idp:AdminInitiateAuth
                      - cognito-idp:AdminConfirmSignUp
                      - cognito-idp:ConfirmSignUp
                      - cognito-idp:ResendConfirmationCode
                      - cognito-idp:AdminRespondToAuthChallenge
                    Resource:
                      - arn:aws:cognito-idp:*:*:*/*
                  - Effect: Allow
                    Action:
                      - "rds:*"
                    Resource: "*"
                  - Effect: Allow
                    Action:
                      - s3:*
                    Resource: "*"
